version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: .docker.env
    container_name: recruitment-db
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
